// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'keyboard': string;
  'output': string;
  'outputSection': string;
  'result': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
